[tool.poetry]
name = "hullnext"
version = "0.1.0"
description = ""
authors = ["Martin Davy <martin.davy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
